development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:pf6d9b5201cca31aefd8d67f25973eea88f5b93731fedcdb7fee5b218b82e8a38@ec2-54-161-0-167.compute-1.amazonaws.com:55159
